name: Command via SSH

on: 
  push:
    paths-ignore: 
      - '.github/**'
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Redeploy Website and Jumpstart
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: ./dbt_jumpstart.sh
          host: ${{ secrets.HOST }}
          username: sahariprasad
          passphrase: ${{ secrets.PASSPHRASE }}
          privateKey: ${{ secrets.PRIVATE_KEY}}
        env:
          CI: true
